@startuml
'https://plantuml.com/class-diagram
' DEFINE THEME:
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

namespace Engine {
    class EngineFactory {
        - {static} _singleton: unique<Engine> = null

        + {static} getInstance(): Engine&
    }
    note top: Singleton
    EngineFactory "1" -- "1" Engine

    class Engine {
        - _eventRegister: EventCallBackRegister
        - _entityManager: EntityManager
        - _systemManager: SystemManager
        - _componentManager: ComponentManager
        - _sceneManager: SceneManager
        - _loop: bool

        + exec(): void
        + quit(): void
    }
    note top : Engine API

    entity Entity
    note top : size_t

    entity Signature
    note top : bitset<MAX_COMPONENT>

    enum EntityName {
        DEFAULT: 0
        EXAMPLE_ENTITY: 1
    }
    enum ClusterName {
        GLOBAL: 0
        GAME: 1
        HOME: 2
        SETTINGS: 3
        ROOM_LIST: 4
        ROOM_CREATE: 5
    }
    /'
        COMPONENTS
    '/
    namespace Component {
        abstract BaseComponent<ComponentType> {
            - {static} idx: Index
            + {static} type: const type_index

            + constructor()
            + {static} setIndex(index: Index): void
            + {static} getIndex(): Index
        }
    }
    /'
        ENTITY MANAGER
    '/
    namespace Entity {

        class EntityManager {
            - _entities: EntityRegister

            + constructor()
            + create(destructor: EntityDestructor&, cluster: ClusterName = ClusterName::GLOBAL, name: EntityName = EntityName::NO_NAME, setNetworkId: bool = false): Entity
            + setNetworkId(entity: Entity, networkId: NetworkId): void
            + getId(networkId: NetworkId): Entity
            + remove(entity: Entity): void
            + remove(name: EntityName): void
            + remove(name: ClusterName): void
            + exist(entity: Entity): bool
            + exist(cluster = ClusterName::GLOBAL: EntityCluster, entity = EntityName::NO_NAME: EntityName): bool
            + hasComponent<ComponentType>(entity: Entity): bool
            + hasComponents<ComponentTypeList...>(entity: Entity): bool
            + getId(name: EntityName): Entity
            + getClusterSize(name: ClusterName): size_t

            - allocate(size: size_t): void
            - getSignatureList(): vector<Signature>
            - getSignature(entity: Entity): const Signature
        }
        note right of EntityManager::replaceIndex
            Replace a private id by a public one
        end note

        class NetworkIdRegister {
            - _counter: NetworkId = 1
            - _freeIds: vector<NetworkId>

            + reserveId(): NetworkId
            + reserveId(id: NetworkId): NetworkId
            + releaseId(id: NetworkId): void
        }

        class EntityRegister {
            - _signatures: vector<Signature>
            - _bookedEntities: vector<EntityBlock>
            - _freeEntities: vector<Entity>
            - _networkIdManager: NetworkIdRegister

            + constructor()
            + allocate(size: size_t): void
            + getSignatureList(): vector<Signature>
            + getSignature(entity: Entity): const Signature
            + create(cluster: EntityCluster, name: EntityName, destructor: EntityDestructor = null, setNetworkId: bool = false): Entity
            ' Reserve public id
            + setNetworkId(entity: Entity, networkId: NetworkId): void
            + getId(networkId: NetworkId): Entity
            + remove(entity: Entity): void
            + remove(name: EntityName): void
            + remove(name: ClusterName): void
            + getId(name: EntityName): Entity
            + getClusterSize(name: ClusterName): size_t
            + exist(entity: Entity): bool
            + exist(entity: EntityName, cluster: EntityCluster = ClusterName::GLOBAL): bool
            + exist(cluster: EntityCluster): bool
        }
        EntityRegister "1" -- "1" EntityManager
        EntityRegister "1" -- "1" NetworkIdRegister
        
        class EntityBlock {
            - _entity: Entity
            - _name: EntityName
            - _cluster: EntityCluster
            - _destructor: EntityDestructor &
            - _networkId: NetworkId

            + constructor(entity: Entity, cluster: ClusterName, name: EntityName, destructor: EntityDestructor &)
            + operator==(name: EntityName): bool
            + operator==(cluster: ClusterName): bool
            + setNetworkId(NetworkId id)
            + getNetworkId(): NetworkId
            + getEntity() Entity
            + setEntity(entity: Entity): void
            + getName(): EntityName
            + getCluster(): ClusterName
            + destroy() void
        }
        note top : using EntityDestructor = std::function<void(Entity, EntityName, EntityCluster)>;
        EntityBlock "0...*" -- "1" EntityRegister
    }
    /'
        COMPONENT MANAGER
    '/
    namespace Component {
        class ComponentManager {
            - _components: array<IComponentTypeRegister>

            + allocate(size: size_t): void
            + register<ComponentType>(): void
            + get<ComponentType>(entity: Entity): ComponentType &
            + getList<ComponentTypeList...>(entity: Entity): tuple<ComponentTypeList...&>
            + add<ComponentType, Args...>(entity: Entity, Args...): void
            + remove<ComponentType>(entity: Entity): void
            + remove<ComponentType>(name: EntityName): void
            + getOwner<ComponentType>(component: ComponentType const&): Entity
            + foreachComponent<ComponentType, Function>(Function &fn): void

            - getRegister<ComponentType>(): ComponentTypeRegister<ComponentType>
            - checkType<ComponentType>(): void
            - checkTypeList<ComponentTypeList...>(): void
        }
        IComponentTypeRegister "0...*" -- "1" ComponentManager

        interface IComponentTypeRegister {
            allocate(size: size_t): void
            remove(entity: Entity): void
        }

        class ComponentTypeRegister<ComponentType> {
            - _list: vector<ComponentType>
            - _componentOwners: vector<Entity>
            - _entityToComponent: map<Entity, size_t>
            - _entitySignatures: vector<Signature>&

            + constructor<ComponentType>(signatures: vector<Signature>&)
            + allocate(size: size_t): void
            + get(entity: Entity): ComponentType &
            + add<Args...>(entity: Entity, Args...): void
            + remove(entity: Entity): void
            + getOwner(component: ComponentType &): Entity
            + getComponents(): vector<ComponentType> &
        }
        IComponentTypeRegister <|-- ComponentTypeRegister
    }

    /'
        SYSTEM MODULE
    '/
    namespace System {
        class SystemManager {
            - _list: vector<shared<AbstractSystem>>
            - _selected: vector<shared<AbstractSystem>>

            + register<SystemType, Args...>(TODO, Args...): SystemType &
            + unRegister<SystemType>(): void
            + select<SystemTypeList...>(): void
            + executeCycle(): void
            + onEntityUpdated(entity: Entity, signature: Signature): void
            + onEntityRemoved(entity: Entity): void
            + getSystem<SystemType>(): SystemType &

            - checkType<SystemType>(): void
        }
        AbstractSystem "0...*" -- "1" SystemManager

        abstract AbstractSystem<SystemType> {
            - {static} _type: const type_index
            - _lastExecTime: TimePoint
            - _requiredComponents: Signature
            - _managedEntities: vector<Entity>
            - _entityToIndex: map<Entity, size_t>
            - _runningFrequency: Time
            - _priority: SystemPriority

            + constructor(runningFrequency: Time = DEFAULT_FREQ, priority: SystemPriority = MEDIUM)
            + getPriority(): Priority
            + getType(): const &type_index
            + refresh(): bool
            + {abstract} run(): void
            + setRequirements<ComponentTypeList...>(): void
            + onEntityUpdated(Entity entity, Signature signature): void
            + onManagedEntityRemoved(Entity entity): void
            + onManagedEntityAdded(Entity entity): void
            + onEntityRemoved(Entity entity): void
            - attachEntity(Entity entity): void
            - detachEntity(Entity entity): void
            # getManagedEntities(): vector<Entity>&
        }
        AbstractSystem "1" -- "1" SystemPriority

        enum SystemPriority {
            LOW,
            MEDIUM,
            HIGH
        }
    }
    /'
        SCENE MODULE
    '/
    namespace Scene {
        class SceneManager {
            - _list: vector<IScene>
            - _currentScene: shared<IScene>
            - _nextScene: shared<IScene>
            - _previousScenes: stack<reference<IScene>>

            + run(): void
            + register<SceneType, Args...>(Args...): void
            + unregister<SceneType>(): void
            + select<SceneType>(closePrevious = true: bool): void
            + selectPrevious(): void
            + havePrevious(): bool
            + getCurrent(): shared<IScene>
            + flushSelection(): void
            + get<SceneType>(): shared<IScene>

            # launchSystemCycle(): void
        }
        IScene "0...*" -- "1" SceneManager

        interface IScene {
            + close(): void
            + open(): void

            + getType(): type_index
            + getCluster(): ClusterName
            + isClosed(): bool
        }

        abstract AbstractScene<SceneType> {
            - _closed: bool
            - _cluster: ClusterName

            + {static} type: type_index

            + constructor(name: ClusterName)
            + {abstract} open(): void
            + close(): void

            + getCluster(): ClusterName
            + isClosed(): bool
            + getType(): type_index
        }
        IScene <|-- AbstractScene
    }
    /'
        EVENT MODULE
    '/
    namespace Engine.Event {
        class EventCallBack<Args> {
            - _event: const &IEvent
            - _callback: & std::function<void(Args...)>

            + constructor(event: const &IEvent, callback: std::function<void(Args)> &)
            + call(args: Args...): void
            + operator==(event: const& IEvent): bool
        }
        note bottom : Représente une action en cas d'événement
        IEventCallBack <|-- EventCallBack

        interface IEventCallBack<Args> {
            + call(args: Args...): void
            + operator==(event: const& IEvent): bool
        }


        class EventCallBackRegister {
            - _callbackList: unordered_map<IEvent, IEventCallBack>
            - _queue: queue<IEvent>

            + register<EventType>(callback: CallbackType): void
            + dispatch<EventType>(Args...): void
            + execQueue(): void
            - checkType<EventType>(): void
        }
        EventCallBackRegister "1" -- "0..*" IEventCallBack
        EventCallBackRegister "1" -- "0..*" IEvent

        interface IEvent {
            + getType(): type_index
        }
        abstract AbstractEvent {
            - {static} type: type_index
            + getType(): type_index
        }
        note right : Représente un événement
        IEvent <|-- AbstractEvent
    }
    namespace Exception {
        class Basic {
            - _message: string

            + constructor(message: string const&)
            + what(): const char *
        }
        std::exception <|-- Basic

        class InvalidType
        class NotFound
        class InvalidParameter
        class FatalError
        class RuntimeError

        Basic <|-- RuntimeError
        Basic <|-- FatalError
        Basic <|-- InvalidParameter
        Basic <|-- InvalidType
        Basic <|-- NotFound
    }
}
namespace Game {
    class GameHandler {
        - onStartGame(e: const StartGameEvent&): void
    }

    namespace GameEvent {
        class StartGameEvent {
            constructor(example: Int)
        }
        Engine.Event.AbstractEvent <|-- StartGameEvent
    }

    namespace GameComponent {
        abstract AbstractSyncComponent<Model> {
            - _modified: bool

            + notifyUpdate(): void
            + isUpdated(): bool
            + {abstract} serialise(): Model
            + override(data: Model const&): void
            + operator=(data: Model const&): void
        }
        Engine.Component.BaseComponent <|-- AbstractSyncComponent
    }
}

@enduml